import { type NFT } from '../types';

export const mockNFTs: NFT[] = [
  {
    id: '1',
    name: 'Pryzen Genesis #001',
    collection: 'Pryzen Genesis Collection',
    image: '/placeholder.svg',
    price: 2.5,
    rarity: 'Legendary',
    status: 'owned',
    tokenId: '001',
    description: 'The first ever Pryzen NFT card, marking the beginning of a new era in digital collectibles. This legendary piece features unique holographic effects and exclusive membership benefits.',
    attributes: [
      { trait_type: 'Background', value: 'Galaxy' },
      { trait_type: 'Border', value: 'Gold' },
      { trait_type: 'Rarity', value: 'Legendary' },
      { trait_type: 'Edition', value: 'Genesis' },
    ],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Pryzen Warrior #045',
    collection: 'Pryzen Warrior Collection',
    image: '/placeholder.svg',
    price: 1.8,
    rarity: 'Epic',
    status: 'auction',
    tokenId: '045',
    description: 'A fierce warrior from the Pryzen universe, equipped with legendary armor and mystical powers. Only the bravest collectors dare to own this epic NFT.',
    attributes: [
      { trait_type: 'Armor', value: 'Mythril' },
      { trait_type: 'Weapon', value: 'Plasma Sword' },
      { trait_type: 'Element', value: 'Fire' },
      { trait_type: 'Power Level', value: '9500' },
    ],
    createdAt: '2024-01-14T15:30:00Z',
  },
  {
    id: '3',
    name: 'Pryzen Mystic #127',
    collection: 'Pryzen Mystic Collection',
    image: '/placeholder.svg',
    price: 1.2,
    rarity: 'Rare',
    status: 'sold',
    tokenId: '127',
    description: 'A mystical being with the power to manipulate reality itself. This rare NFT grants access to exclusive Pryzen events and special voting rights in the community.',
    attributes: [
      { trait_type: 'Magic Type', value: 'Cosmic' },
      { trait_type: 'Crystal', value: 'Amethyst' },
      { trait_type: 'Aura', value: 'Purple' },
      { trait_type: 'Spell Power', value: '7800' },
    ],
    createdAt: '2024-01-13T09:15:00Z',
  },
  {
    id: '4',
    name: 'Pryzen Scout #289',
    collection: 'Pryzen Scout Collection',
    image: '/placeholder.svg',
    price: 0.8,
    rarity: 'Rare',
    status: 'available',
    tokenId: '289',
    description: 'Swift and agile, the Pryzen Scout is known for its incredible speed and stealth abilities. Perfect for collectors who appreciate strategy and cunning.',
    attributes: [
      { trait_type: 'Speed', value: 'Lightning' },
      { trait_type: 'Stealth', value: 'Master' },
      { trait_type: 'Gear', value: 'Advanced' },
      { trait_type: 'Agility', value: '9200' },
    ],
    createdAt: '2024-01-12T14:45:00Z',
  },
  {
    id: '5',
    name: 'Pryzen Guardian #156',
    collection: 'Pryzen Guardian Collection',
    image: '/placeholder.svg',
    price: 1.5,
    rarity: 'Epic',
    status: 'owned',
    tokenId: '156',
    description: 'The protector of the Pryzen realm, wielding ancient powers and unbreakable shields. This epic NFT represents strength and loyalty.',
    attributes: [
      { trait_type: 'Shield', value: 'Adamantine' },
      { trait_type: 'Protection', value: 'Divine' },
      { trait_type: 'Honor', value: 'Legendary' },
      { trait_type: 'Defense', value: '9800' },
    ],
    createdAt: '2024-01-11T16:20:00Z',
  },
  {
    id: '6',
    name: 'Pryzen Apprentice #342',
    collection: 'Pryzen Apprentice Collection',
    image: '/placeholder.svg',
    price: 0.3,
    rarity: 'Common',
    status: 'available',
    tokenId: '342',
    description: 'Every great hero starts somewhere. This common NFT represents the beginning of a journey and the potential for greatness.',
    attributes: [
      { trait_type: 'Learning', value: 'Eager' },
      { trait_type: 'Potential', value: 'High' },
      { trait_type: 'Dedication', value: 'Strong' },
      { trait_type: 'Growth', value: '3500' },
    ],
    createdAt: '2024-01-10T11:30:00Z',
  },
  {
    id: '7',
    name: 'Pryzen Alchemist #078',
    collection: 'Pryzen Alchemist Collection',
    image: '/placeholder.svg',
    price: 1.1,
    rarity: 'Rare',
    status: 'auction',
    tokenId: '078',
    description: 'Master of transmutation and magical formulas, the Pryzen Alchemist can transform the ordinary into the extraordinary.',
    attributes: [
      { trait_type: 'Knowledge', value: 'Ancient' },
      { trait_type: 'Laboratory', value: 'Mystical' },
      { trait_type: 'Formula', value: 'Secret' },
      { trait_type: 'Wisdom', value: '8100' },
    ],
    createdAt: '2024-01-09T13:15:00Z',
  },
  {
    id: '8',
    name: 'Pryzen Dragon #023',
    collection: 'Pryzen Dragon Collection',
    image: '/placeholder.svg',
    price: 3.2,
    rarity: 'Legendary',
    status: 'sold',
    tokenId: '023',
    description: 'The most powerful beings in the Pryzen universe. Owning a Dragon NFT grants ultimate prestige and exclusive access to the Dragon Council.',
    attributes: [
      { trait_type: 'Element', value: 'Cosmic Fire' },
      { trait_type: 'Wings', value: 'Ethereal' },
      { trait_type: 'Breath', value: 'Stardust' },
      { trait_type: 'Power Level', value: '10000' },
    ],
    createdAt: '2024-01-08T08:00:00Z',
  },
  {
    id: '9',
    name: 'Pryzen Merchant #198',
    collection: 'Pryzen Merchant Collection',
    image: '/placeholder.svg',
    price: 0.6,
    rarity: 'Common',
    status: 'available',
    tokenId: '198',
    description: 'The backbone of Pryzen economy, these merchants travel across realms bringing rare goods and valuable information.',
    attributes: [
      { trait_type: 'Goods', value: 'Exotic' },
      { trait_type: 'Trade Routes', value: 'Interdimensional' },
      { trait_type: 'Reputation', value: 'Trusted' },
      { trait_type: 'Wealth', value: '4200' },
    ],
    createdAt: '2024-01-07T19:45:00Z',
  },
  {
    id: '10',
    name: 'Pryzen Phantom #067',
    collection: 'Pryzen Phantom Collection',
    image: '/placeholder.svg',
    price: 2.1,
    rarity: 'Epic',
    status: 'owned',
    tokenId: '067',
    description: 'Ethereal beings that exist between dimensions, Phantoms are mysterious and powerful entities that few have ever encountered.',
    attributes: [
      { trait_type: 'Visibility', value: 'Translucent' },
      { trait_type: 'Phase', value: 'Interdimensional' },
      { trait_type: 'Energy', value: 'Spectral' },
      { trait_type: 'Mystery', value: '9100' },
    ],
    createdAt: '2024-01-06T12:30:00Z',
  },
  {
    id: '11',
    name: 'Pryzen Healer #234',
    collection: 'Pryzen Healer Collection',
    image: '/placeholder.svg',
    price: 0.9,
    rarity: 'Rare',
    status: 'owned',
    tokenId: '234',
    description: 'Blessed with the power to restore and rejuvenate, Healers are essential allies in any Pryzen adventure.',
    attributes: [
      { trait_type: 'Healing Power', value: 'Divine' },
      { trait_type: 'Compassion', value: 'Infinite' },
      { trait_type: 'Staff', value: 'Crystal' },
      { trait_type: 'Restoration', value: '8500' },
    ],
    createdAt: '2024-01-05T17:10:00Z',
  },
  {
    id: '12',
    name: 'Pryzen Novice #456',
    collection: 'Pryzen Novice Collection',
    image: '/placeholder.svg',
    price: 0.4,
    rarity: 'Common',
    status: 'auction',
    tokenId: '456',
    description: 'Fresh-faced and eager to learn, Novices represent the future generation of Pryzen heroes and legends.',
    attributes: [
      { trait_type: 'Enthusiasm', value: 'Boundless' },
      { trait_type: 'Training', value: 'Basic' },
      { trait_type: 'Dreams', value: 'Grand' },
      { trait_type: 'Potential', value: '2800' },
    ],
    createdAt: '2024-01-04T14:25:00Z',
  },
];